Trying to swicth from mcstate to monty 

```{r}
rm(list=ls())

# Load libraries
library(dust2)
library(odin2)
library(monty)
library(dplyr)
library(tidyr)
library(ggplot2)
```

```{r}
# Load model
msr <- odin("~/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/LSTHM project/Extension/RSV_infection_NL/Extended model/Odin2 model.R")
```

```{r}
# Check the model
pars <- list(prop = 0.9)
sys <- dust_system_create(msr(), pars, n_particles = 20, dt = 0.25)
dust_system_set_state_initial(sys)
time <- 0:1825
y <- dust_system_simulate(sys, time)

palette <- c("M1" = "#F2862C",  "M2" = "yellow", "S" = "#8c8cd9", "R" = "#999966", "prop_sero_tot" = "pink")
sero_tot <- dust_unpack_state(sys, y)$R_all
M1_sp <- dust_unpack_state(sys, y)$M1_sp
M2_sp <- dust_unpack_state(sys, y)$M2_sp
S_sp <- dust_unpack_state(sys, y)$S_sp
R_sp <- dust_unpack_state(sys, y)$R_sp
matplot(time, t(sero_tot), type = "l", lty = 1, col = palette[["prop_sero_tot"]],
        xlab = "Time (days)", ylab = "Proportion of children", las = 1)
matlines(time, t(M1_sp), type = "l", lty = 1, col = palette[["M1"]])
matlines(time, t(M2_sp), type = "l", lty = 1, col = palette[["M2"]])
matlines(time, t(S_sp), type = "l", lty = 1, col = palette[["S"]])
matlines(time, t(R_sp), type = "l", lty = 1, col = palette[["R"]])
```

```{r}
data <- read.csv("https://raw.githubusercontent.com/Stijn-A/RSV_serology/master/data/infection_status_csv.txt",
                 sep=",")

# Group age into intervals 
# bi-monthly for 0-2 years and 6-monthly for 2-5 years
data$age_grp <- cut(data$age_days,
                   breaks = c(seq(0,730, by = 30.25*2),
                              seq(909,2000, by = 30.25*6)), 
                   include.lowest = T, right = F)

# Divide by season of birth
spring <- c(3, 4, 5)
summer <- c(6, 7, 8)
autumn <- c (9, 10, 11)
winter <- c(1, 2, 12)

data <- data %>%
  mutate(
    Birth_mo = birthday %>% lubridate::month(),
    season_birth = case_when (Birth_mo %in% spring ~ "spring",
                              Birth_mo %in% summer ~ "summer",
                              Birth_mo %in% autumn ~ "autumn",
                              Birth_mo %in% winter ~ "winter"))

get_midpoint <- function(cut_label) {
  round(mean(as.numeric(unlist(strsplit(gsub("\\(|\\)|\\[|\\]", "", as.character(cut_label)), ",")))))
}

data$xMidpoint <- sapply(data$age_grp, get_midpoint)

# Different groupings
# Get number of cases by age
incidence_data <- data %>% select (age_grp, age_days, infection) %>%
  mutate(N_tot = n()) %>%
  group_by(age_grp) %>%
  reframe(time = round(median(age_days)), 
            N = n(),
            n_infection = sum(infection),
            prop_seroconv = n_infection/N,
            cum_infection = prop_seroconv * N_tot) %>%
  ungroup() %>% 
  distinct()

# Calculate seroprevalence and binomial confidence intervals
incidence_data[,c("seroprev_mean","seroprev_low95","seroprev_up95")] <- binom::binom.confint(incidence_data$n_infection, 
                                                                                             incidence_data$N,
                                                                                             method="exact")[,c("mean","lower","upper")]

incidence_data_season <- data %>% select (age_grp, age_days, infection, season_birth, xMidpoint) %>%
  mutate(N_tot = n()) %>%
  group_by(age_grp, xMidpoint, season_birth) %>%
  summarise(age_mid = round(median(age_days)), 
            N = n(),
            n_infection = sum(infection),
            prop_seroconv = n_infection/N,
            cum_infection = prop_seroconv * N_tot) %>%
  ungroup() %>% 
  distinct()

incidence_data_season[,c("seroprev_mean","seroprev_low95","seroprev_up95")] <- binom::binom.confint(incidence_data_season$n_infection, 
                                                                                             incidence_data_season$N, 
                                                                                             method="exact")[,c("mean","lower","upper")]

incidence_data_season_wide <- incidence_data_season %>% 
  select (!c(age_mid, age_grp, seroprev_mean)) %>%
  pivot_wider(
    names_from = season_birth,
    values_from = c(N , n_infection, prop_seroconv, seroprev_low95, seroprev_up95, cum_infection),
    values_fill = 0
  ) %>%
  rename(time = "xMidpoint")

head(incidence_data_season_wide)
```


```{r}
# Build a filter and test it
filter <- dust_filter_create(msr, time_start = 0, data = incidence_data_season_wide, n_particles = 1000)
dust_likelihood_run(filter, list(spring_comp = 0.003478,
                                summer_comp = 0.00060,
                                autumn_comp = 0.00264,
                                winter_comp = 0.00692, 
                                mu = 0.09,
                                prop = 0.3),
                    save_trajectories = T)
```

```{r}
# Plot the fit
h <- dust_likelihood_last_trajectories(filter)

trajectories <- t(dust_unpack_state(filter, h)$R_all)
sero_conv <- data.frame(incidence_data$time, trajectories[,1])
colnames(sero_conv) <- c("time", "seroconversion")

sero_conv %>% ggplot() +
  geom_line(aes(x = time, y = seroconversion)) +
  geom_point(data = incidence_data, aes(x = time, y = prop_seroconv), col = "red") +
  geom_errorbar(data = incidence_data, aes(x = time, ymax = seroprev_up95, ymin = seroprev_low95), col = "red") +
  labs(x = "Age (days)", y = " Proportion seroconverted\n")
```

```{r}
# Now trying to run an MCMC
# List of inputs
packer <- monty_packer(c("spring_comp", "summer_comp", "autumn_comp", "winter_comp", 
                         "mu", "prop"))

# Likelihood
likelihood <- dust_likelihood_monty(filter, packer, save_trajectories = T)

# Priors
prior <- monty_dsl({
  spring_comp ~ Uniform(0, 0.1)
  summer_comp ~ Uniform(0, 0.1)
  autumn_comp ~ Uniform(0, 0.1)
  winter_comp ~ Uniform(0, 0.1)
  mu ~ Uniform(0.0001, 0.1)
  prop ~ Uniform(0, 1)
})

# Posterior
posterior <- likelihood + prior

# Define a sampler (adaptive MCMC)
vcv <- diag(6) * 0.0004
# sampler <- monty_sampler_random_walk(vcv)
# sampler <- monty_sampler_parallel_tempering(5, vcv, base = NULL)
# sampler <- monty_sampler_hmc(epsilon = 0.1, n_integration_steps = 10)
sampler <- monty_sampler_adaptive(vcv)

# Parallelise the process
runner <- monty_runner_callr(2, progress = T)

# Sample
# samples <- monty_sample(posterior, sampler, 80000, 
#                         initial = c(1e-05, 0.02002, 3e-05, 4e-05, 0.09, 0.5),
#                         n_chains = 2,
#                         runner = runner)

properties <- monty_model_properties(is_stochastic = F)
model <- monty_model(posterior, properties = properties)
samples <- monty_sample(model, sampler, 80000, 
                        initial = c(1e-05, 0.02002, 3e-05, 4e-05, 0.09, 0.5),
                        n_chains = 2,
                        runner = runner)

```

```{r}
# Check mixing
matplot(samples$density, type = "l", lty = 1,
        xlab = "Sample", ylab = "Log posterior probability density")
```

```{r}
# Other diagnostic tools must be imported from other packages
library(posterior)
library(bayesplot)
draws <- as_draws_df(samples)
summarise_draws(draws)
mcmc_trace(draws, facet_args = list(ncol = 1, strip.position = "left"))
```

```{r}
draws_array <- as_draws_array(draws)
# Posterior uncertainty intervals
# Plot them separetly because the values are very difference
mcmc_intervals(draws_array, pars = c("spring_comp", "summer_comp", "autumn_comp", "winter_comp"))
mcmc_intervals(draws_array, pars = "mu")
mcmc_intervals(draws_array, pars = "prop")
```

```{r}
# Univariate marginal posterior distributions
mcmc_hist(draws_array)
```

```{r}
# Trajectories
trajectories <- dust_unpack_state(filter,
                                  samples$observations$trajectories)
sero_conv <- array(trajectories$R_all, c(19, 1000))
```

```{r}
# Plot the fit
matplot(incidence_data$time, sero_conv, type = "l", col = "#00000044", lty = 1,
        xlab = "Age", ylab = "Sero-conversion")
points(x = incidence_data$time, y = incidence_data$prop_seroconv, pch = 19, col = "red")
arrows(x0 = incidence_data$time, y0 = incidence_data$seroprev_low95, 
       x1 = incidence_data$time, y1 = incidence_data$seroprev_up95, 
       angle = 90, code = 3, length = 0.1, col = "red")
```

```{r}
# Tune the sampler
# Define a sampler (random walk)
vcv_tuned <- cov(draws[1:6])
# sampler_tuned <- monty_sampler_random_walk(vcv_tuned)
# 
# # Sample
# samples_tuned <- monty_sample(posterior, sampler_tuned, 120000, 
#                               initial = c(1e-05, 0.02002, 3e-05, 4e-05, 0.09, 0.5),
#                               n_chains = 2,
#                               runner = runner)

runner <- monty_runner_callr(6, progress = T)
sampler_tuned <- monty_sampler_adaptive(vcv_tuned)
samples_tuned <- monty_sample(model, sampler_tuned, 80000, 
                              initial = c(1e-05, 0.02002, 3e-05, 4e-05, 0.09, 0.5),
                              runner = runner,
                              n_chains = 6)
```

```{r}
# Check mixing
matplot(samples_tuned$density, type = "l", lty = 1,
        xlab = "Sample", ylab = "Log posterior probability density")
```

```{r}
# Thin and check mixing
samples_thinned <- monty_samples_thin(samples_tuned, burnin = 12000)

matplot(samples_thinned$density, type = "l", lty = 1,
        xlab = "Sample", ylab = "Log posterior probability density")

dev.copy(jpeg,filename="/Users/juliamayer/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/LSTHM project/Extension/Plots/Checks/monty/Trace log posterior season mu adaptive.png");
dev.off ()
```


```{r}
# Check trace
draws_thinned <- as_draws_df(samples_thinned)
mcmc_trace(draws_thinned, facet_args = list(ncol = 1, strip.position = "left"))
dev.copy(jpeg,filename="/Users/juliamayer/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/LSTHM project/Extension/Plots/Checks/monty/Trace parameters season mu adaptive.png");
dev.off ()
```

```{r}
# Summary
summarise_draws(draws_thinned)
```

```{r}
draws_array_tuned <- as_draws_array(draws_thinned)
# Posterior uncertainty intervals
# Plot them separetly because the values are very difference
mcmc_intervals(draws_array_tuned, pars = c("spring_comp", "summer_comp", "autumn_comp", "winter_comp"))
dev.copy(jpeg,filename="/Users/juliamayer/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/LSTHM project/Extension/Plots/Checks/monty/Uncertainty FOI season mu adaptive.png");
dev.off ()

mcmc_intervals(draws_array_tuned, pars = "mu")
dev.copy(jpeg,filename="/Users/juliamayer/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/LSTHM project/Extension/Plots/Checks/monty/Uncertainty mu season mu adaptive.png");
dev.off ()

mcmc_intervals(draws_array_tuned, pars = "prop")
dev.copy(jpeg,filename="/Users/juliamayer/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/LSTHM project/Extension/Plots/Checks/monty/Uncertainty pi season mu adaptive.png");
dev.off ()
```

```{r}
# Univariate marginal posterior distributions
mcmc_hist(draws_array_tuned)
dev.copy(jpeg,filename="/Users/juliamayer/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/LSTHM project/Extension/Plots/Checks/monty/Marginal posterior distributions season mu adaptive.png");
dev.off ()
```

```{r}
# Trajectories
trajectories <- dust_unpack_state(filter,
                                  samples_thinned$observations$trajectories)
sero_conv <- array(trajectories$R_all, c(19, 1000))
```

```{r}
# Plot the fit
matplot(incidence_data$time, sero_conv, type = "l", col = "#00000044", lty = 1,
        xlab = "Age", ylab = "Sero-conversion", main = "Model fit")
points(x = incidence_data$time, y = incidence_data$prop_seroconv, pch = 19, col = "red")
arrows(x0 = incidence_data$time, y0 = incidence_data$seroprev_low95, 
       x1 = incidence_data$time, y1 = incidence_data$seroprev_up95, 
       angle = 90, code = 3, length = 0.1, col = "red")

dev.copy(jpeg,filename="/Users/juliamayer/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/LSTHM project/Extension/Plots/Checks/monty/Model fit season mu adaptive.png");
dev.off ()
```

```{r}
# By season
# Spring
sero_conv_spring <- array(trajectories$R_sp, c(19, 1000))
matplot(incidence_data_season_wide$time, sero_conv_spring, type = "l", col = "#00000044", lty = 1,
        xlab = "Age", ylab = "Sero-conversion", main = "Model fit - spring")
points(x = incidence_data_season_wide$time, y = incidence_data_season_wide$prop_seroconv_spring, pch = 19, col = "red")
arrows(x0 = incidence_data_season_wide$time, y0 = incidence_data_season_wide$seroprev_low95_spring, 
       x1 = incidence_data_season_wide$time, y1 = incidence_data_season_wide$seroprev_up95_spring, 
       angle = 90, code = 3, length = 0.1, col = "red")

dev.copy(jpeg,filename="/Users/juliamayer/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/LSTHM project/Extension/Plots/Checks/monty/Model fit season spring mu adaptive.png");
dev.off ()
```

```{r}
# Summer
sero_conv_summer <- array(trajectories$R_sm, c(19, 1000))
matplot(incidence_data_season_wide$time, sero_conv_summer, type = "l", col = "#00000044", lty = 1,
        xlab = "Age", ylab = "Sero-conversion", main = "Model fit - summer")
points(x = incidence_data_season_wide$time, y = incidence_data_season_wide$prop_seroconv_summer, pch = 19, col = "red")
arrows(x0 = incidence_data_season_wide$time, y0 = incidence_data_season_wide$seroprev_low95_summer, 
       x1 = incidence_data_season_wide$time, y1 = incidence_data_season_wide$seroprev_up95_summer, 
       angle = 90, code = 3, length = 0.1, col = "red")

dev.copy(jpeg,filename="/Users/juliamayer/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/LSTHM project/Extension/Plots/Checks/monty/Model fit season summer mu adaptive.png");
dev.off ()
```

```{r}
# Autumn
sero_conv_autumn <- array(trajectories$R_au, c(19, 1000))
matplot(incidence_data_season_wide$time, sero_conv_autumn, type = "l", col = "#00000044", lty = 1,
        xlab = "Age", ylab = "Sero-conversion", main = "Model fit - autumn")
points(x = incidence_data_season_wide$time, y = incidence_data_season_wide$prop_seroconv_autumn, pch = 19, col = "red")
arrows(x0 = incidence_data_season_wide$time, y0 = incidence_data_season_wide$seroprev_low95_autumn, 
       x1 = incidence_data_season_wide$time, y1 = incidence_data_season_wide$seroprev_up95_autumn, 
       angle = 90, code = 3, length = 0.1, col = "red")

dev.copy(jpeg,filename="/Users/juliamayer/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/LSTHM project/Extension/Plots/Checks/monty/Model fit season autumn adaptive.png");
dev.off ()
```

```{r}
# Winter
sero_conv_winter <- array(trajectories$R_wt, c(19, 1000))
matplot(incidence_data_season_wide$time, sero_conv_winter, type = "l", col = "#00000044", lty = 1,
        xlab = "Age", ylab = "Sero-conversion", main = "Model fit - winter")
points(x = incidence_data_season_wide$time, y = incidence_data_season_wide$prop_seroconv_winter, pch = 19, col = "red")
arrows(x0 = incidence_data_season_wide$time, y0 = incidence_data_season_wide$seroprev_low95_winter, 
       x1 = incidence_data_season_wide$time, y1 = incidence_data_season_wide$seroprev_up95_winter, 
       angle = 90, code = 3, length = 0.1, col = "red")

dev.copy(jpeg,filename="/Users/juliamayer/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/LSTHM project/Extension/Plots/Checks/monty/Model fit season winter adaptive.png");
dev.off ()
```

```{r}
# Tune the sampler again
# Define a sampler (random walk)
vcv_tuned2 <- cov(draws_thinned[1:6])
sampler_tuned2 <- monty_sampler_adaptive(vcv_tuned2)

# Sample
samples_tuned2 <- monty_sample(model, sampler_tuned2, 120000, 
                              initial = c(1e-05, 0.02002, 3e-05, 4e-05, 0.09, 0.5),
                              n_chains = 2,
                              runner = runner)
```

```{r}
# Check mixing
matplot(samples_tuned2$density, type = "l", lty = 1,
        xlab = "Sample", ylab = "Log posterior probability density")
```


```{r}
# Thin and check mixing
samples_thinned2 <- monty_samples_thin(samples_tuned2, burnin = 12000)

matplot(samples_thinned2$density, type = "l", lty = 1,
        xlab = "Sample", ylab = "Log posterior probability density")

dev.copy(jpeg,filename="/Users/juliamayer/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/LSTHM project/Extension/Plots/Checks/monty/Trace log posterior season mu 2.png");
dev.off ()
```

```{r}
# Check trace
draws_thinned2 <- as_draws_df(samples_thinned2)
mcmc_trace(draws_thinned2, facet_args = list(ncol = 1, strip.position = "left"))
dev.copy(jpeg,filename="/Users/juliamayer/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/LSTHM project/Extension/Plots/Checks/monty/Trace parameters season mu 2.png");
dev.off ()
```

```{r}
# Summary
summarise_draws(draws_thinned2)
```

```{r}
draws_array_tuned2 <- as_draws_array(draws_thinned2)
# Posterior uncertainty intervals
# Plot them separetly because the values are very difference
mcmc_intervals(draws_array_tuned2, pars = c("spring_comp", "summer_comp", "autumn_comp", "winter_comp"))
dev.copy(jpeg,filename="/Users/juliamayer/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/LSTHM project/Extension/Plots/Checks/monty/Uncertainty FOI season mu 2.png");
dev.off ()

mcmc_intervals(draws_array_tuned2, pars = "mu")
dev.copy(jpeg,filename="/Users/juliamayer/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/LSTHM project/Extension/Plots/Checks/monty/Uncertainty mu season mu 2.png");
dev.off ()

mcmc_intervals(draws_array_tuned2, pars = "prop")
dev.copy(jpeg,filename="/Users/juliamayer/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/LSTHM project/Extension/Plots/Checks/monty/Uncertainty pi season mu 2.png");
dev.off ()
```

```{r}
# Univariate marginal posterior distributions
mcmc_hist(draws_array_tuned2)
dev.copy(jpeg,filename="/Users/juliamayer/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/LSTHM project/Extension/Plots/Checks/monty/Marginal posterior distributions season mu 2.png");
dev.off ()
```

```{r}
# Trajectories
trajectories2 <- dust_unpack_state(filter,
                                  samples_thinned2$observations$trajectories)
sero_conv2 <- array(trajectories2$R_all, c(19, 1000))
```

```{r}
# Plot the fit
matplot(incidence_data$time, sero_conv2, type = "l", col = "#00000044", lty = 1,
        xlab = "Age", ylab = "Sero-conversion", main = "Model fit")
points(x = incidence_data$time, y = incidence_data$prop_seroconv, pch = 19, col = "red")

dev.copy(jpeg,filename="/Users/juliamayer/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/LSTHM project/Extension/Plots/Checks/monty/Model fit season mu 2.png");
dev.off ()
```


