Trying to build an MSR model with odin.dust 

```{r}
# Load libraries
rm(list=ls())
set.seed(42)

library(tidyverse)
library(BayesianTools)
library(binom)
# library(plyr)
# library(deSolve)
# library(coda)
# library(lubridate)
library(odin.dust)
library(odin)
library(dplyr)
library (tidyr)
theme_set(theme_minimal())
```

```{r}
# Load model
gen_msr <- odin_dust("~/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/LSTHM project/Extension/RSV_infection_NL/Extended model/Odin model.R")
# gen_msr <- odin_dust("~/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/LSTHM project/Extension/RSV_infection_NL/Extended model/Odin model 1 M comp.R")
```

```{r}
# DATA PREP  ------------------------------------------------------------

data <- read.csv("https://raw.githubusercontent.com/Stijn-A/RSV_serology/master/data/infection_status_csv.txt",
                 sep=",")
# use if offline
#library(readr)
#data <- read_csv("LSHTM/Project/Data/infection_status.csv")

# Group age into intervals 
# bi-monthly for 0-2 years and 6-monthly for 2-5 years
data$agegrp <- cut(data$age_days,
                   breaks = c(seq(0,730, by = 30.25*2),
                              seq(909,2000, by = 30.25*6)), 
                   include.lowest = T, right = F)
# Divide by season of birth
spring <- c(3, 4, 5)
summer <- c(6, 7, 8)
autumn <- c (9, 10, 11)
winter <- c(1, 2, 12)

data <- data %>% 
  mutate(Birth_mo = birthday %>% month(),
         season_birth = case_when (Birth_mo %in% spring ~ "Spring",
                                   Birth_mo %in% summer ~ "Summer",
                                   Birth_mo %in% autumn ~ "Autumn",
                                   Birth_mo %in% winter ~ "Winter"),
         visitnursery_child = case_when (visitnursery_child == 0 ~ FALSE,
                                         visitnursery_child == 1 ~ TRUE))

#different groupings to plot different things
# only grouped by age
data_no_season <- data %>% group_by(agegrp) %>% 
  dplyr::summarise(agemid = round(median(age_days)), # Age midpoint in age group
                   N = n(), # Total N in age group
                   nconv = sum(infection))

# grouped by age and season of birth
data_season <- data %>% group_by(agegrp, season_birth) %>% 
  dplyr::summarise(agemid = round(median(age_days)), # Age midpoint in age group
                   N = n(), # Total N in age group
                   nconv = sum(infection)) # n seroconverted in age group

# Calculate seroprevalence and binomial confidence intervals
data_no_season[,c("seroprev_mean","seroprev_low95","seroprev_up95")] <- binom.confint(data_no_season$nconv, data_no_season$N, method="exact")[,c("mean","lower","upper")]
data_season[,c("seroprev_mean","seroprev_low95","seroprev_up95")] <- binom.confint(data_season$nconv, data_season$N, method="exact")[,c("mean","lower","upper")]
```

```{r}
# Plot the data
data_no_season %>% ggplot() +
  geom_point(aes(x = agemid, y = seroprev_mean)) +
  geom_errorbar(aes(x = agemid, ymin = seroprev_low95, 
                    ymax = seroprev_up95)) +
  ylab("Proportion seroconverted") + xlab("age (days)") 
```

```{r}
# Run the model once
model_fun <- function (estimates) {
 p_new <- list(dt = 1, 
              # M1_sp_ini = 1191 * 0.25, M1_sm_ini = 1191 * 0.25, M1_au_ini = 1191 * 0.25, M1_wt_ini = 1191 * 0.25, 
              # M2_sp_ini = 0, M2_sm_ini = 0, M2_sm_ini = 0, M2_sm_ini = 0,
              # S_sp_ini = 0, S_sm_ini = 0, S_au_ini = 0, S_wt_ini = 0,
              # R_sp_ini = 0, R_sm_ini = 0, R_au_ini = 0, R_wt_ini = 0, mu = 0.1 
              spring_comp = estimates[1], 
              summer_comp = estimates[2], 
              autumn_comp = estimates[3], 
              winter_comp = estimates[4])
msr_model <- gen_msr$new(pars = p_new,
                         time = 1,
                         n_particles = 1L,
                         n_threads = 4L,
                         seed = 1L)

n_times <- 2190
n_particles <- 1L
output <- array(NA, dim = c(msr_model$info()$len, n_particles, n_times))

for (t in seq_len(n_times)) {
  output[ , , t] <- msr_model$run(t)
}

# Turn the result into something intelligible
output_df <- as.data.frame(output)

# Add names
output_df_names <- c("time",
                "M1_sp", "M2_sp", "S_sp", "R_sp",
                "M1_sm", "M2_sm", "S_sm", "R_sm",
                "M1_au", "M2_au", "S_au", "R_au",
                "M1_wt", "M2_wt", "S_wt", "R_wt", "R_all")

# output_df_names <- c("time",
#                 "M_sp", "S_sp", "R_sp",
#                 "M_sm", "S_sm", "R_sm",
#                 "M_au", "S_au", "R_au",
#                 "M_wt", "S_wt", "R_wt", "R_all",
#                 "lambda_spring", "lambda_summer", "lambda_autumn", "lambda_winter",
#                 "spring_component", "summer_component", "autumn_component", "winter_component")

output_df_w_names <- cbind(output_df_names, output_df)

# Transpose and assign names
output_transp <- data.frame(t(output_df_w_names[-1]))
colnames(output_transp) <- output_df_w_names[, 1]

# Get proportion seroconverted at a given age
output_transp <- output_transp %>% rowwise() %>%
  dplyr::mutate(total_pop = sum(c_across(M1_sp:R_wt)),
          prop_sero_tot = R_all / total_pop)

# output_transp <- output_transp %>% group_by(time) %>%
#   mutate(prop_sero_tot = R_all / sum(M_sp, M_sm, M_au, M_wt,
#                                      S_sp, S_sm, S_au, S_wt,
#                                      R_sp, R_sm, R_au, R_wt))
return (output_transp)
}
```

```{r}
# Check the behaviour of the FOI
# output_transp %>% ggplot() +
#   geom_line(aes(x = time, y = lambda_spring), colour = "green") +
#   geom_line(aes(x = time, y = lambda_summer), colour = "orange") +
#   geom_line(aes(x = time, y = lambda_autumn), colour = "yellow") +
#   geom_line(aes(x = time, y = lambda_winter), colour = "blue") +
#   ylim(0.020, 0.0203)

# output_transp %>% ggplot() +
#   geom_line(aes(x = time, y = spring_component), colour = "green") +
#   geom_line(aes(x = time, y = summer_component), colour = "orange") +
#   geom_line(aes(x = time, y = autumn_component), colour = "yellow") +
#   geom_line(aes(x = time, y = winter_component), colour = "blue") +
#   ylim(0.00001, 0.00006)
```

```{r}
# Plot the model output
theta <- c(spring_comp = 0.00001, summer_comp = 0.02002, autumn_comp = 0.00003, winter_comp = 0.00004)
model_output <- model_fun(theta)

model_output %>% ggplot() +
  geom_line(aes(x = time, y = prop_sero_tot), colour = "indianred1") +
  geom_point(data = data_no_season, aes(x = agemid, y = seroprev_mean)) +
  geom_errorbar(data = data_no_season, aes(x = agemid, ymin = seroprev_low95, 
                    ymax = seroprev_up95)) +
  ylab("Proportion seroconverted") + xlab("age (days)") 
```

```{r}
theta <- c(spring_comp = 1, summer_comp = 1, autumn_comp = 1, winter_comp = 1)
model_output <- model_fun(theta)

model_output %>% ggplot() +
  geom_line(aes(x = time, y = prop_sero_tot), colour = "indianred1") +
  geom_point(data = data_no_season, aes(x = agemid, y = seroprev_mean)) +
  geom_errorbar(data = data_no_season, aes(x = agemid, ymin = seroprev_low95, 
                    ymax = seroprev_up95)) +
  ylab("Proportion seroconverted") + xlab("age (days)") 
```

```{r}
# Plot the model output
theta <- c(spring_comp = 0, summer_comp = 0.1, autumn_comp = 0, winter_comp = 0)
model_output <- model_fun(theta)

model_output %>% ggplot() +
  geom_line(aes(x = time, y = prop_sero_tot), colour = "indianred1") +
  geom_point(data = data_no_season, aes(x = agemid, y = seroprev_mean)) +
  geom_errorbar(data = data_no_season, aes(x = agemid, ymin = seroprev_low95, 
                    ymax = seroprev_up95)) +
  ylab("Proportion seroconverted") + xlab("age (days)") 
```

```{r}
# Testing gradient descent
LL_freq = function(x) -loglik(x) # optim searches for parameters, which minimise the function fn --> change the sign of the function

out_freq <- optim(c(0.003478, 0.02002, 0.00264, 0.00692), 
                  LL_freq, 
                  lower = 0.0001 + c(0, 0, 0, 0), 
                  upper = 0.9999 * c(1, 1, 1, 1), 
                  method= 'L-BFGS-B')

out_freq
```


```{r}
# Define likelihood function
loglik <- function(params) {
  
  model_output <- model_fun(params)
  
  # Whole data
  nconv_spring <- data_season$nconv[!is.na(data_season$nconv) & data_season$season_birth == "Spring"] # n seroconverted at each age point  (data)
  N_spring <- data_season$N[!is.na(data_season$nconv) & data_season$season_birth == "Spring"] # total N at each age point  (data) 
  prob_spring <- model_output$R_sp[model_output$time %in% data_season$agemid[data_season$season_birth == "Spring"]] # proportion seroconverted at each age point (model output)
  
  ll_spring <- sum(dbinom(x = nconv_spring,
                       size = N_spring,
                       prob = prob_spring,
                       log = TRUE), na.rm = TRUE)
  
  nconv_summer <- data_season$nconv[!is.na(data_season$nconv) & data_season$season_birth == "Summer"] # n seroconverted at each age point  (data)
  N_summer <- data_season$N[!is.na(data_season$nconv) & data_season$season_birth == "Summer"] # total N at each age point  (data) 
  prob_summer <- model_output$R_sp[model_output$time %in% data_season$agemid[data_season$season_birth == "Summer"]] # proportion seroconverted at each age point (model output)
  
  ll_summer <- sum(dbinom(x = nconv_summer,
                       size = N_summer,
                       prob = prob_summer,
                       log = TRUE), na.rm = TRUE)
  
  nconv_autumn <- data_season$nconv[!is.na(data_season$nconv) & data_season$season_birth == "Autumn"] # n seroconverted at each age point  (data)
  N_autumn <- data_season$N[!is.na(data_season$nconv) & data_season$season_birth == "Autumn"] # total N at each age point  (data) 
  prob_autumn <- model_output$R_sp[model_output$time %in% data_season$agemid[data_season$season_birth == "Autumn"]] # proportion seroconverted at each age point (model output)
  
  ll_autumn <- sum(dbinom(x = nconv_autumn,
                       size = N_autumn,
                       prob = prob_autumn,
                       log = TRUE), na.rm = TRUE)
  
  nconv_winter <- data_season$nconv[!is.na(data_season$nconv) & data_season$season_birth == "Winter"] # n seroconverted at each age point  (data)
  N_winter <- data_season$N[!is.na(data_season$nconv) & data_season$season_birth == "Winter"] # total N at each age point  (data) 
  prob_winter <- model_output$R_sp[model_output$time %in% data_season$agemid[data_season$season_birth == "Winter"]] # proportion seroconverted at each age point (model output)
  
  ll_winter <- sum(dbinom(x = nconv_winter,
                       size = N_winter,
                       prob = prob_winter,
                       log = TRUE), na.rm = TRUE)
  
  ll_all <- ll_spring + ll_summer + ll_autumn + ll_winter
  
  return(ll_all)
  
} 

# Test function
theta <- c(spring_comp = 0.00001, summer_comp = 0.02002, autumn_comp = 0.00003, winter_comp = 0.00004, pi = 0.5)

loglik(theta)

# FITTING -------------------------------------------

# Estimated params
# spring_comp = mean FOI (proportion infected per day) in spring
# summer_comp = mean FOI for children in summer
# autumn_comp = mean FOI for children in autumn
# winter_comp = mean FOI for children in winter
estpars <- c("spring_comp", "summer_comp", "autumn_comp", "winter_comp", "pi") # parameters to estimate, can be modified
index <- which(names(theta) %in% estpars) # index of estimated params

# Priors
lower = c(spring_comp = 0, summer_comp = 0, autumn_comp = 0, winter_comp = 0, pi = 0)
upper = c(spring_comp = 0.1, summer_comp = 0.1, autumn_comp = 0.1, winter_comp = 0.1, pi = 1)

bayesianSetup <- createBayesianSetup(likelihood = loglik, 
                                    lower = lower, 
                                    upper = upper,
                                    names = names(theta[index]))
nchains <- 2
mcmc_settings <- list(iterations = 2*80000, 
                      nrChains = nchains,adapt = T, # running an adaptive MCMC
                      optimize = T)
system.time({trace <- runMCMC(bayesianSetup = bayesianSetup, 
                   sampler = "Metropolis", 
                   settings = mcmc_settings)}) # takes about 3 hours
```

```{r}
# DIAGNOSTICS -----------------------------------------------
plot(trace) 

# burn-in
nburn <- 10000
plot(trace, parametersOnly = TRUE, start = nburn)

# check convergence and correlations
gelmanDiagnostics(trace, plot = TRUE, start = nburn)
correlationPlot(getSample(trace, parametersOnly = TRUE, coda = TRUE, start = nburn), density = "smooth", thin = 50)
marginalPlot(trace, prior = T, singlePanel = T, start = nburn, nDrawsPrior = 1000)

# remove burn-in for trajsim simulation
tracefinal <- getSample(trace, parametersOnly = TRUE, coda = TRUE, start = nburn)
plot(tracefinal)
coda::effectiveSize(tracefinal)

# Posterior summary
summary(tracefinal)

# save the trace
saveRDS(trace, "/Users/juliamayer/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/LSTHM project/Extension/Odin model with 1 M.rds")
```

```{r}
maketrajsim <- function(trace, theta, ndraw, data) {
  
  #Draw n fitted parameter vectors theta from the MCMC object
  sample <- getSample(trace, parametersOnly = TRUE, thin = 1, numSamples = ndraw) #trace is a sampler, parametersOnly = T means that likelihood, posterior and prior values are not provided in the output, thin = thinning parameter
  
  traj.rep <- plyr::adply(.data = sample, .margins = 1, .progress = "text", .parallel = F, .fun = function(x) { #split sample by 1 = rows and apply function
    
    #Define the theta as the estimated parameters from the current draw and the fixed parameters
    theta.sample <- c(x, theta[!is.na(theta)])
    
    #Simulate trajectory for selected theta
    traj <- model_fun(theta.sample) #match.fun extracts the underlying function
    traj <- cbind(as.data.frame(t(x)), traj)
  })
  
  colnames(traj.rep)[1] <- "replicate"
  return(traj.rep)
  
}

trajsim <- maketrajsim(tracefinal, theta, ndraw = 1000)
```

```{r}
# Proportion converted overall
trajquantiles <- plyr::ddply(.data = trajsim, .variables = "time", 
                             function(x) quantile(x[,"prop_sero_tot"], prob = c(0.025, 0.5, 0.975), na.rm=T)) 
colnames(trajquantiles) <- c("agemid", "low95", "median", "up95")

# Overall incidence overtime
trajquantiles_inc <- plyr::ddply(.data = trajsim, .variables = "time", 
                             function(x) quantile(x[,"R_all"], prob = c(0.025, 0.5, 0.975), na.rm=T)) 
colnames(trajquantiles_inc) <- c("agemid", "low95", "median", "up95")


# FOI per birth cohort
lambda_spquantiles <- plyr::ddply(.data = trajsim, .variables = "time",
                                  function(x) quantile(x[,"lambda_spring"], prob = c(0.025, 0.5, 0.975), na.rm=T))
colnames(lambda_spquantiles) <- c("agemid", "low95", "median", "up95")

lambda_smquantiles <- plyr::ddply(.data = trajsim, .variables = "time",
                                  function(x) quantile(x[,"lambda_summer"], prob = c(0.025, 0.5, 0.975), na.rm=T))
colnames(lambda_smquantiles) <- c("agemid", "low95", "median", "up95")

lambda_auquantiles <- plyr::ddply(.data = trajsim, .variables = "time",
                                  function(x) quantile(x[,"lambda_autumn"], prob = c(0.025, 0.5, 0.975), na.rm=T))
colnames(lambda_auquantiles) <- c("agemid", "low95", "median", "up95")

lambda_wtquantiles <- plyr::ddply(.data = trajsim, .variables = "time",
                                  function(x) quantile(x[,"lambda_winter"], prob = c(0.025, 0.5, 0.975), na.rm=T))
colnames(lambda_wtquantiles) <- c("agemid", "low95", "median", "up95")

# Parameter estimates
Pquantiles <- plyr::ddply(.data = trajsim, .variables = "time", 
                          function(x) quantile(x[,"spring_comp"], prob = c(0.025, 0.5, 0.975), na.rm=T)) 
colnames(Pquantiles) <- c("agemid", "low95", "median", "up95")

Mquantiles <- plyr::ddply(.data = trajsim, .variables = "time", 
                          function(x) quantile(x[,"summer_comp"], prob = c(0.025, 0.5, 0.975), na.rm=T)) 
colnames(Mquantiles) <- c("agemid", "low95", "median", "up95")

Aquantiles <- plyr::ddply(.data = trajsim, .variables = "time", 
                          function(x) quantile(x[,"autumn_comp"], prob = c(0.025, 0.5, 0.975), na.rm=T)) 
colnames(Aquantiles) <- c("agemid", "low95", "median", "up95")

Wquantiles <- plyr::ddply(.data = trajsim, .variables = "time", 
                          function(x) quantile(x[,"winter_comp"], prob = c(0.025, 0.5, 0.975), na.rm=T)) 
colnames(Wquantiles) <- c("agemid", "low95", "median", "up95")


# Cumulative proportion seroconverted by season of birth
spring_conv_quantiles <- plyr::ddply(.data = trajsim, .variables = "time",
                                     function(x) quantile(x[,"R_sp"], prob = c(0.025, 0.5, 0.975), na.rm=T))
colnames(spring_conv_quantiles) <- c("agemid", "low95", "median", "up95")

summer_conv_quantiles <- plyr::ddply(.data = trajsim, .variables = "time",
                                     function(x) quantile(x[,"R_sm"], prob = c(0.025, 0.5, 0.975), na.rm=T))
colnames(summer_conv_quantiles) <- c("agemid", "low95", "median", "up95")

autumn_conv_quantiles <- plyr::ddply(.data = trajsim, .variables = "time",
                                     function(x) quantile(x[,"R_au"], prob = c(0.025, 0.5, 0.975), na.rm=T))
colnames(autumn_conv_quantiles) <- c("agemid", "low95", "median", "up95")

winter_conv_quantiles <- plyr::ddply(.data = trajsim, .variables = "time",
                                     function(x) quantile(x[,"R_wt"], prob = c(0.025, 0.5, 0.975), na.rm=T))
colnames(winter_conv_quantiles) <- c("agemid", "low95", "median", "up95")

# Incident proportion seroconverted by season of birth
# spring_conv_quantiles_inc <- plyr::ddply(.data = trajsim, .variables = "time", 
#                                      function(x) quantile(x[,"R_sp"], prob = c(0.025, 0.5, 0.975), na.rm=T)) 
# colnames(spring_conv_quantiles_inc) <- c("agemid", "low95", "median", "up95")
# 
# summer_conv_quantiles_inc <- plyr::ddply(.data = trajsim, .variables = "time", 
#                                      function(x) quantile(x[,"R_sm"], prob = c(0.025, 0.5, 0.975), na.rm=T)) 
# colnames(summer_conv_quantiles_inc) <- c("agemid", "low95", "median", "up95")
# 
# autumn_conv_quantiles_inc <- plyr::ddply(.data = trajsim, .variables = "time", 
#                                      function(x) quantile(x[,"R_au"], prob = c(0.025, 0.5, 0.975), na.rm=T)) 
# colnames(autumn_conv_quantiles_inc) <- c("agemid", "low95", "median", "up95")
# 
# winter_conv_quantiles_inc <- plyr::ddply(.data = trajsim, .variables = "time", 
#                                      function(x) quantile(x[,"R_wt"], prob = c(0.025, 0.5, 0.975), na.rm=T)) 
# colnames(winter_conv_quantiles_inc) <- c("agemid", "low95", "median", "up95")

# Plot fit and FOI
# Whole dataset
fit <- ggplot() + theme_bw() + ggtitle("Model fit") +
  geom_point(data = data_no_season, aes(x = agemid, y = seroprev_mean)) +
  geom_linerange(data = data_no_season, aes(x = agemid, ymin = seroprev_low95, ymax = seroprev_up95)) +
  geom_ribbon(data = trajquantiles_inc, aes(x = agemid, ymin = low95, ymax = up95), fill = "red", alpha = 0.3) +
  geom_line(data = trajquantiles_inc, aes(x = agemid, y = median), color = "red") +
  xlab("age (days)") + ylab("proportion seroconverted") 

fit
```

```{r}
# Saving the useful files ------------------------------------------------------------
path <- "/Users/juliamayer/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/LSTHM project/Extension/CSV files/2 M odin/"
# write.csv(lambda_spquantiles, paste0(path, "strat_lambda_sp.csv"))
# write.csv(lambda_smquantiles, paste0(path, "strat_lambda_sm.csv"))
# write.csv(lambda_auquantiles, paste0(path, "strat_lambda_au.csv"))
# write.csv(lambda_wtquantiles, paste0(path, "strat_lambda_wt.csv"))

write.csv(Pquantiles, paste0(path, "strat_Pquantiles.csv"))
write.csv(Mquantiles, paste0(path, "strat_Mquantiles.csv"))
write.csv(Aquantiles, paste0(path, "strat_Aquantiles.csv"))
write.csv(Wquantiles, paste0(path, "strat_Wquantiles.csv"))

# Cumulative seroconversion
write.csv(trajquantiles, paste0(path, "strat_trajquantiles.csv"))
write.csv(trajsim, paste0(path, "strat_trajsim.csv"))
write.csv(spring_conv_quantiles, paste0(path, "strat_spring_conv_tot.csv"))
write.csv(summer_conv_quantiles, paste0(path, "strat_summer_conv_tot.csv"))
write.csv(autumn_conv_quantiles, paste0(path, "strat_autumn_conv_tot.csv"))
write.csv(winter_conv_quantiles, paste0(path, "strat_winter_conv_tot.csv"))

# Incident seroconversion
# write.csv(trajquantiles_inc, paste0(path, "Incidence/strat_trajquantiles_inc.csv"))
# write.csv(trajsim, paste0(path, "Incidence/strat_trajsim.csv"))
# write.csv(spring_conv_quantiles_inc, paste0(path, "Incidence/strat_spring_conv_inc.csv"))
# write.csv(summer_conv_quantiles_inc, paste0(path, "Incidence/strat_summer_conv_inc.csv"))
# write.csv(autumn_conv_quantiles_inc, paste0(path, "Incidence/strat_autumn_conv_inc.csv"))
# write.csv(winter_conv_quantiles_inc, paste0(path, "Incidence/strat_winter_conv_inc.csv"))
```


```{r}
lambda_sp <- ggplot() + theme_bw() + ggtitle("FOI for the spring birth cohort (no daycare)") +
  geom_ribbon(data = lambda_spquantiles, aes(x = agemid, ymin = low95, ymax = up95), fill = "red", alpha = 0.3) +
  geom_line(data = lambda_spquantiles, aes(x = agemid, y = median), color = "red") +
  xlab("age (days)") + ylab("FOI") + xlim(0, 365)
lambda_sp
```

```{r}
lambda_sm <- ggplot() + theme_bw() + ggtitle("FOI for the summer birth cohort (no daycare)") +
  geom_ribbon(data = lambda_smquantiles, aes(x = agemid, ymin = low95, ymax = up95), fill = "red", alpha = 0.3) +
  geom_line(data = lambda_smquantiles, aes(x = agemid, y = median), color = "red") +
  xlab("age (days)") + ylab("FOI") + xlim(0, 365)
lambda_sm
```

```{r}
lambda_au <- ggplot() + theme_bw() + ggtitle("FOI for the autumn birth cohort (no daycare)") +
  geom_ribbon(data = lambda_auquantiles, aes(x = agemid, ymin = low95, ymax = up95), fill = "red", alpha = 0.3) +
  geom_line(data = lambda_auquantiles, aes(x = agemid, y = median), color = "red") +
  xlab("age (days)") + ylab("FOI") + xlim(0, 365)
lambda_au
```

```{r}
lambda_wt <- ggplot() + theme_bw() + ggtitle("FOI for the winter birth cohort (no daycare)") +
  geom_ribbon(data = lambda_wtquantiles, aes(x = agemid, ymin = low95, ymax = up95), fill = "red", alpha = 0.3) +
  geom_line(data = lambda_wtquantiles, aes(x = agemid, y = median), color = "red") +
  xlab("age (days)") + ylab("FOI") + xlim(0, 365)
lambda_wt
```

```{r}
# Testing the likelihood function
theta1 <- c(spring_comp = 0.00001, summer_comp = 0.02002, autumn_comp = 0.00003, winter_comp = 0.00004)

log1 <- loglik(theta1)

likelihood_values <- data.frame(spring_comp = double(),
                                summer_comp = double(), 
                                autumn_comp = double(),
                                winter_comp = double (),
                                loglikelihood = double ())

likelihood_values <- likelihood_values %>% add_row(spring_comp = theta1[1], 
                                                   summer_comp = theta1[2],
                                                   autumn_comp = theta1[3],
                                                   winter_comp = theta1[4],
                                                   loglikelihood = log1)

theta2 <- c(spring_comp = 0.003478, summer_comp = 0.00060, autumn_comp = 0.00264, winter_comp = 0.00692) # Values from old model

log2 <- loglik(theta2)

likelihood_values <- likelihood_values %>% add_row(spring_comp = theta2[1], 
                                                   summer_comp = theta2[2],
                                                   autumn_comp = theta2[3],
                                                   winter_comp = theta2[4],
                                                   loglikelihood = log2)

theta3 <- c(spring_comp = 0.000078, summer_comp = 0.00060, autumn_comp = 0.034, winter_comp = 0.03)

log3 <- loglik(theta3)

likelihood_values <- likelihood_values %>% add_row(spring_comp = theta3[1], 
                                                   summer_comp = theta3[2],
                                                   autumn_comp = theta3[3],
                                                   winter_comp = theta3[4],
                                                   loglikelihood = log3)

theta4 <- c(spring_comp = 0.1, summer_comp = 0.00060, autumn_comp = 0.1, winter_comp = 0.1)

log4 <- loglik(theta4)

likelihood_values <- likelihood_values %>% add_row(spring_comp = theta4[1], 
                                                   summer_comp = theta4[2],
                                                   autumn_comp = theta4[3],
                                                   winter_comp = theta4[4],
                                                   loglikelihood = log4)

theta5 <- c(spring_comp = 0.00001, summer_comp = 0.00060, autumn_comp = 0.00001, winter_comp = 0.00001)

log5 <- loglik(theta5)

likelihood_values <- likelihood_values %>% add_row(spring_comp = theta5[1], 
                                                   summer_comp = theta5[2],
                                                   autumn_comp = theta5[3],
                                                   winter_comp = theta5[4],
                                                   loglikelihood = log5)

theta6 <- c(spring_comp = 0, summer_comp = 0.00060, autumn_comp = 0, winter_comp = 0)

log6 <- loglik(theta6)

likelihood_values <- likelihood_values %>% add_row(spring_comp = theta6[1], 
                                                   summer_comp = theta6[2],
                                                   autumn_comp = theta6[3],
                                                   winter_comp = theta6[4],
                                                   loglikelihood = log6)

theta7 <- c(spring_comp = 0, summer_comp = 0.10, autumn_comp = 0, winter_comp = 0)

log7 <- loglik(theta7)

likelihood_values <- likelihood_values %>% add_row(spring_comp = theta7[1], 
                                                   summer_comp = theta7[2],
                                                   autumn_comp = theta7[3],
                                                   winter_comp = theta7[4],
                                                   loglikelihood = log7)
```

```{r}
# Check likelihood varying spring
n = 100
likelihood_values_list <- list()
set.seed(34)

for (i in 1:n) {
    # ... make some data
    theta <- c(spring_comp = runif(n = 1, min = 0, max = 0.1), 
              summer_comp = 0.00060, 
              autumn_comp = 0.00264, 
              winter_comp = 0.00692)
    log <- loglik(theta)
    dat <- data.frame(spring_comp = theta[1], 
                       summer_comp = theta[2],
                       autumn_comp = theta[3],
                       winter_comp = theta[4],
                      loglikelihood = log)
    likelihood_values_list [[i]] <- dat # add it to your list
}

likelihood_values <- do.call(rbind, likelihood_values_list)

likelihood_values %>% ggplot() +
  geom_line(aes(x = spring_comp, y = loglikelihood)) # +
 # geom_point(aes(x=0.003478, y=-237.64), colour="blue")
```

```{r}
# Check likelihood varying summer
n = 100
likelihood_values_list <- list()
set.seed(34)

for (i in 1:n) {
    # ... make some data
    theta <- c(spring_comp = 0.00003478,
              summer_comp = runif(n = 1, min = 0, max = 0.1), 
              autumn_comp = 0.00264, 
              winter_comp = 0.00692)
    log <- loglik(theta)
    dat <- data.frame(spring_comp = theta[1], 
                       summer_comp = theta[2],
                       autumn_comp = theta[3],
                       winter_comp = theta[4],
                      loglikelihood = log)
    likelihood_values_list [[i]] <- dat # add it to your list
}

likelihood_values <- do.call(rbind, likelihood_values_list)

likelihood_values %>% ggplot() +
  geom_line(aes(x = summer_comp, y = loglikelihood)) # +
  # geom_point(aes(x=0.00060, y=-237.64), colour="blue")
```

