Trying to build an MSR model with odin.dust 

```{r}
rm(list=ls())

# Load libraries
library(odin.dust)
library(odin)
library(dplyr)
library (tidyr)
library(ggplot2)
```

```{r}
# Load model
gen_msr <- odin_dust("~/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/LSTHM project/Extension/RSV_infection_NL/Extended model/Odin model.R")
```

# Running the MSIR model with dust
```{r}
p_new <- list(dt = 1 
              # M1_sp_ini = 1191 * 0.25, M1_sm_ini = 1191 * 0.25, M1_au_ini = 1191 * 0.25, M1_wt_ini = 1191 * 0.25, 
              # M2_sp_ini = 0, M2_sm_ini = 0, M2_sm_ini = 0, M2_sm_ini = 0,
              # S_sp_ini = 0, S_sm_ini = 0, S_au_ini = 0, S_wt_ini = 0,
              # R_sp_ini = 0, R_sm_ini = 0, R_au_ini = 0, R_wt_ini = 0, # beta = 0.4, gamma = 0.1, mu = 0.1 
              # winter_comp = 0.03
              )
msr_model <- gen_msr$new(pars = p_new ,
                         time = 1,
                         n_particles = 1L,
                         n_threads = 4L,
                         seed = 1L)

#res <- msir_model$run(365)
```

```{r}
n_times <- 2190
n_particles <- 1L
x <- array(NA, dim = c(msr_model$info()$len, n_particles, n_times))

for (t in seq_len(n_times)) {
  x[ , , t] <- msr_model$run(t)
}
time <- x[1, 1, ]
#x <- x[-1, , ]

# par(mar = c(4.1, 5.1, 0.5, 0.5), las = 1)
# cols <- c(M = "#F2862C", S = "#8c8cd9", R = "#999966")
# matplot(time, t(x[1, , ]), type = "l",
#          xlab = "Time", ylab = "Number of individuals",
#          col = cols[["M"]], lty = 1, ylim = range(x))
# matlines(time, t(x[2, , ]), col = cols[["S"]], lty = 1)
# matlines(time, t(x[3, , ]), col = cols[["R"]], lty = 1)
# legend("left", lwd = 1, col = cols, legend = names(cols), bty = "n")
```

```{r}
# Turn the result into something intelligible
x_df <- as.data.frame(x)

# Add names
x_df_names <- c("time",
                "M1_sp", "M2_sp", "S_sp", "R_sp",
                "M1_sm", "M2_sm", "S_sm", "R_sm",
                "M1_au", "M2_au", "S_au", "R_au",
                "M1_wt", "M2_wt", "S_wt", "R_wt", "R_all")

x_df_w_names <- cbind(x_df_names, x_df)

# Transpose and assign names
x_transp <- data.frame(t(x_df_w_names[-1]))
colnames(x_transp) <- x_df_w_names[, 1]

# Calculate proportion seroconverted
x_transp <- x_transp %>% mutate %>% rowwise() %>%
  dplyr::mutate(total_pop = sum(c_across(M1_sp:R_wt)),
          prop_sero_tot = R_all)
```

```{r}
palette <- c("M1" = "#F2862C",  "M2" = "yellow", "S" = "#8c8cd9", "R" = "#999966", "prop_sero_tot" = "pink")
x_transp %>% ggplot(aes(x = time)) +
  geom_line(aes(y = M1_sp, colour = "M1")) + 
  geom_line(aes(y = M2_sp, colour = "M2")) + 
  geom_line(aes(y = S_sp, colour = "S")) + 
  geom_line(aes(y = R_sp, colour = "R")) + 
  geom_line(aes(y = prop_sero_tot, colour = "prop_sero_tot")) + 
  labs(title = "Model progression for the spring cohort", x = "Age",
       y = "Number of individuals", colour = "State") +
  theme_light() +
  scale_colour_manual(values = palette)
```

```{r}
palette <- c("M1" = "#F2862C", "M2" = "#cc0044", "S" = "#8c8cd9", "R" = "#999966")
x_transp %>% ggplot(aes(x = time)) +
  geom_line(aes(y = M1_sm, colour = "M1")) + 
  geom_line(aes(y = M2_sm, colour = "M2")) + 
  geom_line(aes(y = S_sm, colour = "S")) + 
  geom_line(aes(y = R_sm, colour = "R")) + 
  labs(title = "Model progression for the summer cohort", x = "Age",
       y = "Number of individuals", colour = "State") +
  theme_light() +
  scale_colour_manual(values = palette)
```

```{r}
palette <- c("M1" = "#F2862C", "M2" = "#cc0044", "S" = "#8c8cd9", "R" = "#999966")
x_transp %>% ggplot(aes(x = time)) +
  geom_line(aes(y = M1_au, colour = "M1")) + 
  geom_line(aes(y = M2_au, colour = "M2")) + 
  geom_line(aes(y = S_au, colour = "S")) + 
  geom_line(aes(y = R_au, colour = "R")) + 
  labs(title = "Model progression for the autumn cohort", x = "Age",
       y = "Number of individuals", colour = "State") +
  theme_light() +
  scale_colour_manual(values = palette)
```

```{r}
palette <- c("M1" = "#F2862C", "M2" = "#cc0044", "S" = "#8c8cd9", "R" = "#999966")
x_transp %>% ggplot(aes(x = time)) +
  geom_line(aes(y = M1_wt, colour = "M1")) + 
  geom_line(aes(y = M2_wt, colour = "M2")) + 
  geom_line(aes(y = S_wt, colour = "S")) + 
  geom_line(aes(y = R_wt, colour = "R")) + 
  labs(title = "Model progression for the winter cohort", x = "Age",
       y = "Number of individuals", colour = "State") +
  theme_light() +
  scale_colour_manual(values = palette)
```

```{r}
# Check that the total is constant
x_transp <- x_transp %>% group_by(time) %>%
  mutate(N = sum(M1_sp, M2_sp, S_sp, R_sp,
                 M1_sm, M2_sm, S_sm, R_sm,
                 M1_au, M2_au, S_au, R_au,
                 M1_wt, M2_wt, S_wt, R_wt))
```

```{r}
# Get total seroconverted at an age
x_transp <- x_transp %>% group_by(time) %>%
  mutate(total_sero = sum(R_sp, R_sm, R_au, R_wt))

# Get total incident cases at an age, total and by season
x_transp <- x_transp %>% ungroup() %>%
  mutate(prev_totalcases = lag(total_sero),
         daily_cases = total_sero - prev_totalcases,
         prev_totalcases_sp = lag(R_sp),
         daily_cases_sp = R_sp - prev_totalcases_sp,
         prev_totalcases_sm = lag(R_sm),
         daily_cases_sm = R_sm - prev_totalcases_sm,
         prev_totalcases_au = lag(R_au),
         daily_cases_au = R_au - prev_totalcases_au,
         prev_totalcases_wt = lag(R_wt),
         daily_cases_wt = R_wt - prev_totalcases_wt) %>%
  select(!c(prev_totalcases, prev_totalcases_sp, prev_totalcases_sm,
            prev_totalcases_au, prev_totalcases_wt))

```

```{r}
# Same thing but using odin instead of odin.dust
msr_test <- odin("~/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/LSTHM project/Extension/RSV_infection_NL/Extended model/Odin model.R")

test <- msr_test$new(M1_sp_ini = 1191 * 0.25, M1_sm_ini = 1191 * 0.25, 
                     M1_au_ini = 1191 * 0.25, M1_wt_ini = 1191 * 0.25, 
                     winter_comp = 0.03,  mu = 0.1)

sir_col <- c("#8c8cd9", "#cc0044", "#999966", "turquoise")
x_res <- test$run(0:2000)
par(mar = c(4.1, 5.1, 0.5, 0.5), las = 1)
matplot(x_res[, 1], x_res[, 3:6], xlab = "Time", ylab = "Number of individuals",
        type = "l", col = sir_col, lty = 1)
legend("topright", lwd = 1, col = sir_col, legend = c("M1", "M2", "S", "R"), bty = "n")
```

```{r}
# Trying to read in and the data and put it in the right format
library (mcstate)
data <- read.csv("https://raw.githubusercontent.com/Stijn-A/RSV_serology/master/data/infection_status_csv.txt",
                 sep=",")

# Group age into intervals 
# bi-monthly for 0-2 years and 6-monthly for 2-5 years
data$age_grp <- cut(data$age_days,
                   breaks = c(seq(0,730, by = 30.25*2),
                              seq(909,2000, by = 30.25*6)), 
                   include.lowest = T, right = F)

# Divide by season of birth
spring <- c(3, 4, 5)
summer <- c(6, 7, 8)
autumn <- c (9, 10, 11)
winter <- c(1, 2, 12)

data <- data %>%
  mutate(
    Birth_mo = birthday %>% lubridate::month(),
    season_birth = case_when (Birth_mo %in% spring ~ "spring",
                              Birth_mo %in% summer ~ "summer",
                              Birth_mo %in% autumn ~ "autumn",
                              Birth_mo %in% winter ~ "winter"))

get_midpoint <- function(cut_label) {
  round(mean(as.numeric(unlist(strsplit(gsub("\\(|\\)|\\[|\\]", "", as.character(cut_label)), ",")))))
}

data$xMidpoint <- sapply(data$age_grp, get_midpoint)

# Different groupings
# Get number of cases by age
incidence_data <- data %>% select (age_grp, age_days, infection, xMidpoint) %>%
  mutate(N_tot = n()) %>%
  group_by(age_grp, xMidpoint) %>%
  summarise(age_mid = round(median(age_days)), 
            N = n(),
            n_infection = sum(infection),
            prop_seroconv = n_infection/N,
            cum_infection = prop_seroconv * N_tot) %>%
  ungroup() %>% 
  distinct() %>%
  mutate(incidence = c(0,diff(cum_infection))) %>%
  mutate(incidence = case_when(incidence >= 0 ~ round(incidence),
                               TRUE ~ 0))

# Get number of cases by age and season of birth
incidence_data_season <- data %>% select (age_grp, age_days, infection, season_birth, xMidpoint) %>%
  mutate(N_tot = n()) %>%
  group_by(age_grp, xMidpoint, season_birth) %>%
  summarise(age_mid = round(median(age_days)), 
            N = n(),
            n_infection = sum(infection),
            prop_seroconv = n_infection/N,
            cum_infection = prop_seroconv * N_tot) %>%
  ungroup() %>% 
  distinct() %>%
  mutate(incidence = c(0,diff(cum_infection))) %>%
  mutate(incidence = case_when(incidence >= 0 ~ round(incidence),
                               TRUE ~ 0))

incidence_data_season_wide <- incidence_data_season %>% select (!c(age_mid, age_grp)) %>%
  pivot_wider(
    names_from = season_birth,
    values_from = c(N , n_infection, prop_seroconv, cum_infection, incidence),
    values_fill = 0
  )

# Put it in the right format?
model_data <- particle_filter_data(data = incidence_data,
                                   initial_time = 0,
                                   time = "age_mid",
                                   rate = 1)
rmarkdown::paged_table(model_data)

model_data_season <- particle_filter_data(data = incidence_data_season_wide,
                                   initial_time = 0,
                                   time = "xMidpoint",
                                   rate = 1)
rmarkdown::paged_table(model_data_season)
```

```{r}
# Plot data by birth cohort
incidence_data_season %>% filter (xMidpoint <= 2*365) %>%
  ggplot() +
  geom_point(aes(x = xMidpoint, y = prop_seroconv)) +
  facet_wrap(~season_birth) +
  labs(title = "Proportion seroconverted by age", x = "\nAge (days)",
       y = "Seroconversion (%)\n") +
  theme_light()
```


```{r}
# Comparison function
case_compare <- function(state, observed, pars = NULL){
  #  exp_noise <- 1e6
  # 
  # total_sero_modelled <- state[18, , drop = T]
  # total_incidence_modelled <- c(0, diff(total_sero_modelled))
  # seroprevalence_observed <- observed$cum_infection
  # incidence_observed <- observed$incidence
  # lambda <- total_sero_modelled  +
  # rexp(n = length(total_sero_modelled ), rate = exp_noise)
  # dpois(x = seroprevalence_observed, lambda = lambda, log = T) # This is OK for incidence, not sure about prevalence
  
  # lambda <- total_incidence_modelled  +
  # rexp(n = length(total_incidence_modelled ), rate = exp_noise)
  # dpois(x = incidence_observed, lambda = lambda, log = T)
  
  
  # Whole data
  nconv <- observed$n_infection # n seroconverted at each age point  (data)
  N <- observed$N # total N at each age point  (data)
  prob <- state[18, , drop = T] #/ colSums(state[2:17, , drop = T]) # proportion seroconverted at each age point (model output) - all seroconverted divided by total population
  
   # Data by season of birth
  nconv_spring <- observed$n_infection_spring
  N_spring <- observed$N_spring
  prob_spring <- state[5, , drop = T]
  ll_spring <- dbinom(x = nconv_spring,
                      size = N_spring,
                      prob = prob_spring,
                      log = TRUE)
  
  nconv_summer <- observed$n_infection_summer
  N_summer <- observed$N_summer
  prob_summer <- state[9, , drop = T]
  ll_summer <- dbinom(x = nconv_summer,
                      size = N_summer,
                      prob = prob_summer,
                      log = TRUE)
  
  nconv_autumn <- observed$n_infection_autumn
  N_autumn <- observed$N_autumn
  prob_autumn <- state[13, , drop = T]
  ll_autumn <- dbinom(x = nconv_autumn,
                      size = N_autumn,
                      prob = prob_autumn,
                      log = TRUE)
  
  nconv_winter <- observed$n_infection_winter
  N_winter <- observed$N_winter
  prob_winter <- state[17, , drop = T] 
  ll_winter <- dbinom(x = nconv_winter,
                      size = N_winter,
                      prob = prob_winter,
                      log = TRUE)
  
  ll_spring + ll_summer + ll_autumn + ll_winter
  
  # dbinom(x = nconv,
  #                     size = N,
  #                     prob = prob,
  #                     log = TRUE)
  
}

```

```{r}
# Investigations

# Based on vignette
 exp_noise <- 1e6

total_sero_modelled <- x[14, , ]
total_incidence_modelled <- c(0, diff(total_sero_modelled))
seroprevalence_observed <- round(model_data$cum_infection)
incidence_observed <- round(model_data$incidence)
lambda <- total_incidence_modelled  +
rexp(n = length(total_incidence_modelled ), rate = exp_noise)
poisson <- dpois(x = incidence_observed, lambda = lambda, log = T)

# Based on Fabienne
nconv <- model_data$n_infection # n seroconverted at each age point  (data)
N <- model_data$N # total N at each age point  (data)
prob <- x[14, , ] / colSums(x[2:13, , ]) # proportion seroconverted at each age point (model output)
# prob <- observed$prop_seroconv

ll <- dbinom(x = nconv,
           size = N,
           prob = prob,
           log = TRUE)

sum(dbinom(x = nconv,
           size = N,
           prob = prob,
           log = TRUE), na.rm = TRUE) # this returns "Expected a vector of length 100 for 'index' but given 1" --> removed sum

nconv_spring <- model_data_season$n_infection[model_data_season$season_birth == "Spring"] 
N_spring <- model_data_season$N[model_data_season$season_birth == "Spring"]
prob_spring <- x[5, , ] / colSums(x[2:5, , ]) 
  ll_spring <- dbinom(x = nconv_spring,
                      size = N_spring,
                      prob = prob_spring,
                      log = TRUE)
  
nconv_summer <- model_data_season$n_infection[model_data_season$season_birth == "Summer"] 
N_summer <- model_data_season$N[model_data_season$season_birth == "Summer"]
prob_summer <- x[5, , ] / colSums(x[2:5, , ]) 
  ll_summer <- dbinom(x = nconv_summer,
                      size = N_summer,
                      prob = prob_summer,
                      log = TRUE)
  
nconv_autumn <- model_data_season$n_infection[model_data_season$season_birth == "Autumn"] 
N_autumn <- model_data_season$N[model_data_season$season_birth == "Autumn"]
prob_autumn <- x[5, , ] / colSums(x[2:5, , ]) 
  ll_autumn <- dbinom(x = nconv_autumn,
                      size = N_autumn,
                      prob = prob_autumn,
                      log = TRUE)
  
nconv_winter <- model_data_season$n_infection[model_data_season$season_birth == "Winter"] 
N_winter <- model_data_season$N[model_data_season$season_birth == "Winter"]
prob_winter <- x[5, , ] / colSums(x[2:5, , ]) 
  ll_winter <- dbinom(x = nconv_winter,
                      size = N_winter,
                      prob = prob_winter,
                      log = TRUE)
  
ll_sum <- ll_spring + ll_summer + ll_winter + ll_autumn

case_compare_test <- function(state, observed, pars = NULL){
  
  # Whole data
  nconv <- observed$n_infection # n seroconverted at each age point  (data)
  N <- observed$N # total N at each age point  (data)
  prob <- state[18, , ] / colSums(state[2:17, ,  ]) # proportion seroconverted at each age point (model output) - all seroconverted divided by total population
 # prob <- observed$prop_seroconv
  
   # Data by season of birth
  nconv_spring <- observed$n_infection_spring
  N_spring <- observed$N_spring
  prob_spring <- state[5, , ] / colSums(state[2:5, , ]) 
  ll_spring <- dbinom(x = nconv_spring,
                      size = N_spring,
                      prob = prob_spring,
                      log = TRUE)
  
  nconv_summer <- observed$n_infection_summer
  N_summer <- observed$N_summer
  prob_summer <- state[9, , ] / colSums(state[6:9, , ])
  ll_summer <- dbinom(x = nconv_summer,
                      size = N_summer,
                      prob = prob_summer,
                      log = TRUE)
  
  nconv_autumn <- observed$n_infection_autumn
  N_autumn <- observed$N_autumn
  prob_autumn <- state[13, , ] / colSums(state[10:13, , ])
  ll_autumn <- dbinom(x = nconv_autumn,
                      size = N_autumn,
                      prob = prob_autumn,
                      log = TRUE)
  
  nconv_winter <- observed$n_infection_winter
  N_winter <- observed$N_winter
  prob_winter <- state[17, , ] / colSums(state[14:17, , ]) 
  ll_winter <- dbinom(x = nconv_winter,
                      size = N_winter,
                      prob = prob_winter,
                      log = TRUE)
  
  ll_spring + ll_summer + ll_autumn + ll_winter
  
}

case_compare_test(x, model_data_season)
```

```{r}
# Set up a particle filter
n_particles <- 100
filter <- particle_filter$new(data = model_data_season,
                              model = gen_msr, 
                              n_particles = n_particles,
                              compare = case_compare,
                              seed = 1L)
```

```{r}
# Run the filter
dt = 1
filter$run(save_history = T, pars = list(dt=dt)) # This is so low! (-90716.07 when using prevalence, -4771.088 for incidence)
```

```{r}
# Testing different values for the filter
old_summer_ll <- filter$run(save_history = T, pars = list(dt=dt,
                                         spring_comp = 0.00001,
                                         summer_comp = 0.00060,
                                         autumn_comp = 0.00003,
                                         winter_comp = 0.00004))

old_all_ll <- filter$run(save_history = T, pars = list(dt=dt,
                                         spring_comp = 0.003478,
                                         summer_comp = 0.00060,
                                         autumn_comp = 0.00264,
                                         winter_comp = 0.00692))

old_all_pi_ll <- filter$run(save_history = T, pars = list(dt=dt,
                                         spring_comp = 0.003478,
                                         summer_comp = 0.00060,
                                         autumn_comp = 0.00264,
                                         winter_comp = 0.00692,
                                         pi = 0.95))
```


```{r}
plot_particle_filter <- function(history, true_history, times, obs_end = NULL) {
  if (is.null(obs_end)) {
    obs_end <- max(times)
  }

  par(mar = c(4.1, 5.1, 0.5, 0.5), las = 1)
  cols <- c(M1_sp = "#8c8cd9", M2_sp = "turquoise", S_sp = "#cc0044", R_sp = "#999966", prop_sero_tot = "pink")
  # cols <- c(M_sp = "#8c8cd9", S_sp = "#cc0044", R_sp = "#999966", R_all = "pink")
  matplot(times, t(history[2, , -1]) %>% unique(), type = "l",
          xlab = "Time", ylab = "Number of individuals",
          col = cols[["M1_sp"]], lty = 1, ylim = c(0,2))
  matlines(times, t(history[3, , -1]), col = cols[["M2_sp"]], lty = 1)
  matlines(times, t(history[4, , -1]), col = cols[["S_sp"]], lty = 1)
  matlines(times, t(history[5, , -1]), col = cols[["R_sp"]], lty = 1)
  matlines(times, t(history[18, , -1]), col = cols[["prop_sero_tot"]], lty = 1)
  matpoints(t(true_history[1]), t(true_history[14]), pch = 19, cols = c("black", "black"))
  legend("left", lwd = 1, col = cols, legend = names(cols), bty = "n")
  
}

plot_particle_filter(filter$history(), model_data_season, incidence_data_season_wide$xMidpoint)
```


```{r}
# Use MCMC to infer parameter values
# Define a truncated Gamma distribution function for mu
dtruncgamma <- function(x, shape, rate, lower, upper) {
  if (x < lower || x > upper) {
    return(0)
  } else {
    # Calculate the untruncated gamma density
    density <- dgamma(x, shape = shape, rate = rate)
    # Calculate the normalization factor
    normalization <- pgamma(upper, shape = shape, rate = rate) - pgamma(lower, shape = shape, rate = rate)
    return(density / normalization)
  }
}

# Define parameters first
spring_comp <- pmcmc_parameter("spring_comp", initial = 0.000001, max = 0.1, min = 0, prior = function(p)
  dunif(p, max = 0.1, min = 0))
summer_comp <- pmcmc_parameter("summer_comp", initial = 0.000202, max = 0.1, min = 0, prior = function(p)
  dunif(p, max = 0.1, min = 0))
autumn_comp <- pmcmc_parameter("autumn_comp", initial = 0.000001, max = 0.1, min = 0, prior = function(p)
  dunif(p, max = 0.1, min = 0))
winter_comp <- pmcmc_parameter("winter_comp", initial = 0.000001, max = 0.1, min = 0, prior = function(p)
  dunif(p, max = 0.1, min = 0))
mu <- pmcmc_parameter("mu", initial = 0.02, max = 0.1, min = 0, prior = function(p)
  dunif(p, max = 0.2, min = 0))
  # dtruncgamma(p, shape = 2.5, rate = 1/30.0, lower = 1/10, upper = 1/180)) # Try a truncated Gamma distribution like Fabienne
pi <- pmcmc_parameter("pi", initial = 0.9, max = 1, min = 0, prior = function(p)
   dunif(p, max = 1, min = 0))
  # gtools::ddirichlet(p, alpha = 1))

proposal_matrix <- diag(0.1, 5)
mcmc_pars <- pmcmc_parameters$new(list(spring_comp = spring_comp, 
                                       summer_comp = summer_comp,
                                       autumn_comp = autumn_comp,
                                       winter_comp = winter_comp,
                                     # mu = mu,
                                       pi = pi),
                                  proposal_matrix)
# Chain parameters
n_steps <- 3e4
n_burnin <- 10000
control <- pmcmc_control(
  n_steps, 
  save_state = T,
  save_trajectories = T,
  progress = T)

# Run it
pmcmc_run <-pmcmc(mcmc_pars, filter, control = control)
```

```{r}
# remove burn-in and thin the four chains
processed_chains <- pmcmc_thin(pmcmc_run, burnin = n_burnin, thin = 2)
parameter_mean_hpd <- apply(processed_chains$pars, 2, mean)
parameter_mean_hpd
```

```{r}
# Analyse the results
mcmc1 <- coda::as.mcmc(cbind(pmcmc_run$probabilities, pmcmc_run$pars))

summary(mcmc1)
```

```{r}
coda::effectiveSize(mcmc1)
```

```{r}
1 - coda::rejectionRate(mcmc1) # Is this good?
```

```{r}
plot(mcmc1) # run this in the console
```


```{r}
# Tuning the MCMC
proposal_matrix <- cov(pmcmc_run$pars)
mcmc_pars <- mcstate::pmcmc_parameters$new(
  list(spring_comp = spring_comp, 
       summer_comp = summer_comp,
       autumn_comp = autumn_comp,
       winter_comp = winter_comp,
     #  mu = mu,
       pi = pi),
  proposal_matrix)
proposal_matrix
```

Now let's run four independent chains with these proposals:
```{r}
control <- pmcmc_control(
  n_steps,
  save_state = T,
  save_trajectories = T,
  progress = T,
  n_chains = 4
)

pmcmc_tuned_run <- pmcmc(mcmc_pars, filter, control = control)
```

```{r}
mcmc2 <- coda::as.mcmc(cbind(
  pmcmc_tuned_run$probabilities, pmcmc_tuned_run$pars))

summary(mcmc2)
```

```{r}
coda::effectiveSize(mcmc2)
```

```{r}
plot(mcmc2) # run this in the console
```


```{r}
1 - coda::rejectionRate(mcmc2) # Is this better???? YES!
```

```{r}
coda::autocorr.plot(mcmc2, lag.max = 500)
```

```{r}
# Check correlation between parameters
lattice::levelplot(mcmc2, col.regions = heat.colors(100))
```


```{r}
# Check if the chains converged using a sample from the posterior distribution
mcmc_sample <- pmcmc_sample(pmcmc_tuned_run, n_sample = 500)

par(mfrow = c(4, 2), mar = c(3, 3, 1, 1), mgp = c(1.5, 0.5, 0), bty = "n")
plot(pmcmc_tuned_run$pars[, "winter_comp"], type = "l", xlab = "Iteration",
     ylab = "winter_comp")
plot(pmcmc_tuned_run$pars[, "spring_comp"], type = "l", xlab = "Iteration",
     ylab = "spring_comp")
plot(pmcmc_tuned_run$pars[, "summer_comp"], type = "l", xlab = "Iteration",
     ylab = "summer_comp")
plot(pmcmc_tuned_run$pars[, "autumn_comp"], type = "l", xlab = "Iteration",
     ylab = "autumn_comp")
 # plot(pmcmc_tuned_run$pars[, "mu"], type = "l", xlab = "Iteration",
 #      ylab = "mu")
plot(pmcmc_tuned_run$pars[, "pi"], type = "l", xlab = "Iteration",
     ylab = "pi")
hist(mcmc_sample$pars[, "winter_comp"], main = "", xlab = "winter_comp",
     freq = FALSE)
hist(mcmc_sample$pars[, "spring_comp"], main = "", xlab = "spring_comp",
     freq = FALSE)
hist(mcmc_sample$pars[, "summer_comp"], main = "", xlab = "summer_comp",
     freq = FALSE)
hist(mcmc_sample$pars[, "autumn_comp"], main = "", xlab = "autumn_comp",
     freq = FALSE)
 # hist(mcmc_sample$pars[, "mu"], main = "", xlab = "mu",
 #      freq = FALSE)
hist(mcmc_sample$pars[, "pi"], main = "", xlab = "pi",
     freq = FALSE)
```

```{r}
# Compare with the data
times <- c(0, incidence_data$age_mid)
cols <- c(`M1 spring` = "#8c8cd9", `M2 spring` = "turquoise", `S spring` = "#cc0044", `R spring` = "#999966", `Total prop \nseroconverted` = "pink")

state <- mcmc_sample$trajectories$state

prop_seroconv <-  t(state[18, , -1])

par(mfrow = c(1, 2), mar = c(3, 3, 1, 1), mgp = c(1.5, 0.5, 0), bty = "n")
matplot(times, t(state[2, , ]), type = "l", lty = 1, col = cols["M1 spring"],
        ylim = c(0, max(t(state[18, , ])) * 1.2), xlab = "Day", ylab = "Proportion of individuals")
matlines(times, t(state[3, , ]), lty = 1, col = cols["M2 spring"])
matlines(times, t(state[4, , ]), lty = 1, col = cols["S spring"])
matlines(times, t(state[5, , ]), lty = 1, col = cols["R spring"])
matlines(times, t(state[18, , ]), lty = 1, col = cols["Total prop \nseroconverted"])
legend("right", lwd = 1, col = cols, legend = names(cols), bty = "n")

matplot(model_data$age_mid_start, prop_seroconv, type = "l", lty = 1, col = grey(0.7, 0.2),
        xlab = "Day", ylab = "Proportion of seroconverted children", ylim = c(0, 1.2))
points(model_data$age_mid_start, model_data$prop_seroconv, pch = 20)
```

```{r}
# Compare fit by season of birth
# Spring
prop_seroconv_sp <-  t(state[5, , -1])
matplot(model_data_season$xMidpoint_start, prop_seroconv_sp, type = "l", lty = 1, col = grey(0.7, 0.2),
        xlab = "Day", ylab = "Proportion of seroconverted children", main = "Spring birth cohort",
        ylim = c(0, 1.2))
points(model_data_season$xMidpoint_start, model_data_season$prop_seroconv_spring, pch = 20)

# Summer
prop_seroconv_sm <-  t(state[9, , -1])
matplot(model_data_season$xMidpoint_start, prop_seroconv_sm, type = "l", lty = 1, col = grey(0.7, 0.2),
        xlab = "Day", ylab = "Proportion of seroconverted children", main = "Summer birth cohort",
        ylim = c(0, 1.2))
points(model_data_season$xMidpoint_start, model_data_season$prop_seroconv_summer, pch = 20)

# Autumn
prop_seroconv_au <-  t(state[13, , -1])
matplot(model_data_season$xMidpoint_start, prop_seroconv_au, type = "l", lty = 1, col = grey(0.7, 0.2),
        xlab = "Day", ylab = "Proportion of seroconverted children", main = "Autumn birth cohort",
        ylim = c(0, 1.2))
points(model_data_season$xMidpoint_start, model_data_season$prop_seroconv_autumn, pch = 20)

# Winter
prop_seroconv_wt <-  t(state[17, , -1])
prop_seroconv_wt_test <-  t(state[18, , ])
matplot(model_data_season$xMidpoint_start, prop_seroconv_wt, type = "l", lty = 1, col = grey(0.7, 0.2),
        xlab = "Day", ylab = "Proportion of seroconverted children", main = "Winter birth cohort",
        ylim = c(0, 1.2))
points(model_data_season$xMidpoint_start, model_data_season$prop_seroconv_winter, pch = 20)
```


```{r}
parameters <- mcmc_sample$pars
```

```{r}
# Look at one sample
single_sample <- pmcmc_sample(pmcmc_tuned_run, n_sample = 1)

state_single <- single_sample$trajectories$state

prop_seroconv <-  (state_single[18, , -1])

par(mfrow = c(1, 2), mar = c(3, 3, 1, 1), mgp = c(1.5, 0.5, 0), bty = "n")
matplot(times, (state_single[2, , ]), type = "l", lty = 1, col = cols["M1_sp"],
        ylim = c(0, max(t(state[18, , ])) * 1.2), xlab = "Day", ylab = "Number of individuals")
matlines(times, (state_single[3, , ]), lty = 1, col = cols["M2_sp"])
matlines(times, (state_single[4, , ]), lty = 1, col = cols["S_sp"])
matlines(times, (state_single[5, , ]), lty = 1, col = cols["R_sp"])
matlines(times, (state_single[18, , ]), lty = 1, col = cols["prop_sero_tot"])
legend("left", lwd = 1, col = cols, legend = names(cols), bty = "n")

matplot(model_data$age_mid_start, prop_seroconv, type = "l", lty = 1, col = grey(0.7, 0.2),
        xlab = "Day", ylab = "Number of cases", ylim = c(0, 1.2))
points(model_data$age_mid_start, model_data$prop_seroconv, pch = 20)
```

```{r}
# Parameter estimates
hpd <- apply(pmcmc_tuned_run$pars, 2, quantile, prob = c(0.025, 0.5, 0.975), na.rm=T) 
rownames(hpd) <- c("low95", "median", "up95")

# Get the mean highest probability distribution
mean_hpd <- apply(pmcmc_tuned_run$pars, 2, mean)

lower_95_hpd <- apply(pmcmc_tuned_run$pars, 2, quantile, probs = 0.05)

upper_95_hpd <- apply(pmcmc_tuned_run$pars, 2, quantile, probs = 0.95)

summary_hpd <- rbind(mean_hpd, lower_95_hpd, upper_95_hpd)
summary_hpd
```

```{r}
# Seroconversion estimates
seroconversion <- list()

for (i in 1:length(pmcmc_tuned_run$trajectories$time)){
  age_midpoint <- pmcmc_tuned_run$trajectories$time[i]
  
  low95_sp <- quantile(pmcmc_tuned_run$trajectories$state[5, , i], 0.05)
  median_sp <- quantile(pmcmc_tuned_run$trajectories$state[5, , i], 0.5)
  up95_sp <- quantile(pmcmc_tuned_run$trajectories$state[5, , i], 0.95)
  
  low95_sm <- quantile(pmcmc_tuned_run$trajectories$state[9, , i], 0.05)
  median_sm <- quantile(pmcmc_tuned_run$trajectories$state[9, , i], 0.5)
  up95_sm <- quantile(pmcmc_tuned_run$trajectories$state[9, , i], 0.95)
  
  low95_au <- quantile(pmcmc_tuned_run$trajectories$state[13, , i], 0.05)
  median_au <- quantile(pmcmc_tuned_run$trajectories$state[13, , i], 0.5)
  up95_au <- quantile(pmcmc_tuned_run$trajectories$state[13, , i], 0.95)
  
  low95_wt <- quantile(pmcmc_tuned_run$trajectories$state[17, , i], 0.05)
  median_wt <- quantile(pmcmc_tuned_run$trajectories$state[17, , i], 0.5)
  up95_wt <- quantile(pmcmc_tuned_run$trajectories$state[17, , i], 0.95)
  
  combined <- data.frame(age_midpoint = age_midpoint,
                         low95_sp, median_sp, up95_sp, 
                         low95_sm, median_sm, up95_sm, 
                         low95_au, median_au, up95_au, 
                         low95_wt, median_wt, up95_wt)
  
  seroconversion[[i]] <- combined
}

seroconversion_df <- do.call("rbind", seroconversion)
rownames(seroconversion_df) <- NULL
```

```{r}
# Save files
path <- "/Users/juliamayer/Library/CloudStorage/OneDrive-Charité-UniversitätsmedizinBerlin/LSTHM project/Extension/CSV files/2 M odin/mcstate/"

write.csv(summary_hpd, paste0(path, "highest probability distribution, seasonal fit.csv"), row.names = F)
write.csv(seroconversion_df, paste0(path, "seroconversion by age, seasonal fit.csv"), row.names = F)
```

